// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           pgtype.UUID
	ActorUserID  pgtype.UUID
	Action       string
	TargetEntity string
	TargetID     pgtype.UUID
	Details      pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type Bookmark struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Category struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type Comment struct {
	ID        pgtype.UUID
	ContentID pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Content struct {
	ID                 pgtype.UUID
	Title              string
	Description        pgtype.Text
	ContentType        string
	CategoryID         pgtype.UUID
	DistrictID         pgtype.UUID
	LocationID         pgtype.UUID
	SourceType         string
	SourceUrl          pgtype.Text
	AuthorUserID       pgtype.UUID
	Status             string
	ModerationStatus   string
	VerificationStatus string
	PublishedAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ContributorProfile struct {
	UserID                 pgtype.UUID
	Level                  string
	Points                 int32
	TrustScore             int32
	ApprovedCount          int32
	RejectedCount          int32
	ReportCount            int32
	ViolationCount         int32
	FeaturedCount          int32
	IsFoundingContributor  bool
	FoundingBadgeGrantedAt pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type Device struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DeviceToken pgtype.Text
	DeviceType  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type District struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Event struct {
	ContentID        pgtype.UUID
	EventName        string
	EventDate        pgtype.Timestamptz
	StartTime        pgtype.Text
	EndTime          pgtype.Text
	OrganizerName    string
	OrganizerContact pgtype.Text
	InterestedCount  int32
}

type Follow struct {
	FollowerUserID pgtype.UUID
	FollowedUserID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Grievance struct {
	ID                pgtype.UUID
	ComplainantUserID pgtype.UUID
	ContactEmail      string
	Category          string
	Description       string
	ContentID         pgtype.UUID
	Status            string
	ResolutionNotes   pgtype.Text
	ResolvedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Like struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Location struct {
	ID         pgtype.UUID
	Name       string
	DistrictID pgtype.UUID
	Latitude   float64
	Longitude  float64
	CreatedAt  pgtype.Timestamptz
}

type ModerationResult struct {
	ContentID         pgtype.UUID
	AutoModerated     bool
	TextToxicityScore float64
	ImageSafetyScore  float64
	FlagsRaised       []string
	Decision          string
	ProcessedAt       pgtype.Timestamptz
}

type Photo struct {
	ContentID  pgtype.UUID
	PhotoCount int32
	PhotoUrls  []string
	CaptionEn  pgtype.Text
	CaptionTa  pgtype.Text
}

type Report struct {
	ID             pgtype.UUID
	ContentID      pgtype.UUID
	ReporterUserID pgtype.UUID
	Reason         string
	Description    pgtype.Text
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Story struct {
	ContentID      pgtype.UUID
	Headline       string
	Body           string
	SinglePhotoUrl pgtype.Text
}

type User struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserProfile struct {
	UserID    pgtype.UUID
	FullName  string
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserSession struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	RefreshToken string
	DeviceInfo   pgtype.Text
	IsRevoked    bool
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type VideoLink struct {
	ContentID       pgtype.UUID
	Platform        string
	ExternalVideoID string
	CanonicalUrl    string
	EmbedHtml       pgtype.Text
	ThumbnailUrl    pgtype.Text
	DurationSeconds pgtype.Int4
	LinkStatus      string
	LastCheckedAt   pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}
