// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_user_id, action, target_entity, target_id, details)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, action, created_at
`

type CreateAuditLogParams struct {
	ActorUserID  pgtype.UUID
	Action       string
	TargetEntity string
	TargetID     pgtype.UUID
	Details      pgtype.Text
}

type CreateAuditLogRow struct {
	ID        pgtype.UUID
	Action    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetEntity,
		arg.TargetID,
		arg.Details,
	)
	var i CreateAuditLogRow
	err := row.Scan(&i.ID, &i.Action, &i.CreatedAt)
	return i, err
}

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (content_id, user_id)
VALUES ($1, $2)
ON CONFLICT (content_id, user_id) DO NOTHING
RETURNING content_id, user_id, created_at
`

type CreateBookmarkParams struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, createBookmark, arg.ContentID, arg.UserID)
	var i Bookmark
	err := row.Scan(&i.ContentID, &i.UserID, &i.CreatedAt)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (content_id, user_id, body)
VALUES ($1, $2, $3)
RETURNING id, content_id, user_id, body, created_at
`

type CreateCommentParams struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
	Body      string
}

type CreateCommentRow struct {
	ID        pgtype.UUID
	ContentID pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment, arg.ContentID, arg.UserID, arg.Body)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createContent = `-- name: CreateContent :one

INSERT INTO content (title, description, content_type, category_id, district_id, location_id, source_type, source_url, author_user_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, title, description, content_type, category_id, district_id, location_id, source_type, source_url, author_user_id, status, created_at
`

type CreateContentParams struct {
	Title        string
	Description  pgtype.Text
	ContentType  string
	CategoryID   pgtype.UUID
	DistrictID   pgtype.UUID
	LocationID   pgtype.UUID
	SourceType   string
	SourceUrl    pgtype.Text
	AuthorUserID pgtype.UUID
	Status       string
}

type CreateContentRow struct {
	ID           pgtype.UUID
	Title        string
	Description  pgtype.Text
	ContentType  string
	CategoryID   pgtype.UUID
	DistrictID   pgtype.UUID
	LocationID   pgtype.UUID
	SourceType   string
	SourceUrl    pgtype.Text
	AuthorUserID pgtype.UUID
	Status       string
	CreatedAt    pgtype.Timestamptz
}

// --- CONTENT CREATION & LISTING ---
func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (CreateContentRow, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.Title,
		arg.Description,
		arg.ContentType,
		arg.CategoryID,
		arg.DistrictID,
		arg.LocationID,
		arg.SourceType,
		arg.SourceUrl,
		arg.AuthorUserID,
		arg.Status,
	)
	var i CreateContentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentType,
		&i.CategoryID,
		&i.DistrictID,
		&i.LocationID,
		&i.SourceType,
		&i.SourceUrl,
		&i.AuthorUserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createContributorProfile = `-- name: CreateContributorProfile :one

INSERT INTO contributor_profiles (user_id)
VALUES ($1)
RETURNING user_id, level, points, trust_score
`

type CreateContributorProfileRow struct {
	UserID     pgtype.UUID
	Level      string
	Points     int32
	TrustScore int32
}

// --- CONTRIBUTOR PROFILES ---
func (q *Queries) CreateContributorProfile(ctx context.Context, userID pgtype.UUID) (CreateContributorProfileRow, error) {
	row := q.db.QueryRow(ctx, createContributorProfile, userID)
	var i CreateContributorProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.Points,
		&i.TrustScore,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one

INSERT INTO devices (user_id, device_token, device_type)
VALUES ($1, $2, $3)
ON CONFLICT (device_token) DO UPDATE SET updated_at = NOW()
RETURNING id, device_token, device_type
`

type CreateDeviceParams struct {
	UserID      pgtype.UUID
	DeviceToken pgtype.Text
	DeviceType  string
}

type CreateDeviceRow struct {
	ID          pgtype.UUID
	DeviceToken pgtype.Text
	DeviceType  string
}

// --- DEVICES ---
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (CreateDeviceRow, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UserID, arg.DeviceToken, arg.DeviceType)
	var i CreateDeviceRow
	err := row.Scan(&i.ID, &i.DeviceToken, &i.DeviceType)
	return i, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (content_id, event_name, event_date, start_time, end_time, organizer_name, organizer_contact)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING content_id, event_name, event_date, start_time, end_time, organizer_name, organizer_contact
`

type CreateEventParams struct {
	ContentID        pgtype.UUID
	EventName        string
	EventDate        pgtype.Timestamptz
	StartTime        pgtype.Text
	EndTime          pgtype.Text
	OrganizerName    string
	OrganizerContact pgtype.Text
}

type CreateEventRow struct {
	ContentID        pgtype.UUID
	EventName        string
	EventDate        pgtype.Timestamptz
	StartTime        pgtype.Text
	EndTime          pgtype.Text
	OrganizerName    string
	OrganizerContact pgtype.Text
}

// --- EVENTS SPECIFIC ---
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ContentID,
		arg.EventName,
		arg.EventDate,
		arg.StartTime,
		arg.EndTime,
		arg.OrganizerName,
		arg.OrganizerContact,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ContentID,
		&i.EventName,
		&i.EventDate,
		&i.StartTime,
		&i.EndTime,
		&i.OrganizerName,
		&i.OrganizerContact,
	)
	return i, err
}

const createFollow = `-- name: CreateFollow :one
INSERT INTO follows (follower_user_id, followed_user_id)
VALUES ($1, $2)
ON CONFLICT (follower_user_id, followed_user_id) DO NOTHING
RETURNING follower_user_id, followed_user_id, created_at
`

type CreateFollowParams struct {
	FollowerUserID pgtype.UUID
	FollowedUserID pgtype.UUID
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) (Follow, error) {
	row := q.db.QueryRow(ctx, createFollow, arg.FollowerUserID, arg.FollowedUserID)
	var i Follow
	err := row.Scan(&i.FollowerUserID, &i.FollowedUserID, &i.CreatedAt)
	return i, err
}

const createGrievance = `-- name: CreateGrievance :one

INSERT INTO grievances (complainant_user_id, contact_email, category, description, content_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, complainant_user_id, contact_email, category, description, content_id, status, created_at
`

type CreateGrievanceParams struct {
	ComplainantUserID pgtype.UUID
	ContactEmail      string
	Category          string
	Description       string
	ContentID         pgtype.UUID
}

type CreateGrievanceRow struct {
	ID                pgtype.UUID
	ComplainantUserID pgtype.UUID
	ContactEmail      string
	Category          string
	Description       string
	ContentID         pgtype.UUID
	Status            string
	CreatedAt         pgtype.Timestamptz
}

// --- GRIEVANCES (COMPLIANCE) ---
func (q *Queries) CreateGrievance(ctx context.Context, arg CreateGrievanceParams) (CreateGrievanceRow, error) {
	row := q.db.QueryRow(ctx, createGrievance,
		arg.ComplainantUserID,
		arg.ContactEmail,
		arg.Category,
		arg.Description,
		arg.ContentID,
	)
	var i CreateGrievanceRow
	err := row.Scan(
		&i.ID,
		&i.ComplainantUserID,
		&i.ContactEmail,
		&i.Category,
		&i.Description,
		&i.ContentID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createLike = `-- name: CreateLike :one

INSERT INTO likes (content_id, user_id)
VALUES ($1, $2)
ON CONFLICT (content_id, user_id) DO NOTHING
RETURNING content_id, user_id, created_at
`

type CreateLikeParams struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
}

// --- SOCIAL & ENGAGEMENT ---
func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, createLike, arg.ContentID, arg.UserID)
	var i Like
	err := row.Scan(&i.ContentID, &i.UserID, &i.CreatedAt)
	return i, err
}

const createModerationResult = `-- name: CreateModerationResult :one
INSERT INTO moderation_results (content_id, auto_moderated, text_toxicity_score, image_safety_score, flags_raised, decision)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (content_id) DO UPDATE SET
  auto_moderated = EXCLUDED.auto_moderated,
  text_toxicity_score = EXCLUDED.text_toxicity_score,
  image_safety_score = EXCLUDED.image_safety_score,
  flags_raised = EXCLUDED.flags_raised,
  decision = EXCLUDED.decision,
  processed_at = NOW()
RETURNING content_id, decision, processed_at
`

type CreateModerationResultParams struct {
	ContentID         pgtype.UUID
	AutoModerated     bool
	TextToxicityScore float64
	ImageSafetyScore  float64
	FlagsRaised       []string
	Decision          string
}

type CreateModerationResultRow struct {
	ContentID   pgtype.UUID
	Decision    string
	ProcessedAt pgtype.Timestamptz
}

func (q *Queries) CreateModerationResult(ctx context.Context, arg CreateModerationResultParams) (CreateModerationResultRow, error) {
	row := q.db.QueryRow(ctx, createModerationResult,
		arg.ContentID,
		arg.AutoModerated,
		arg.TextToxicityScore,
		arg.ImageSafetyScore,
		arg.FlagsRaised,
		arg.Decision,
	)
	var i CreateModerationResultRow
	err := row.Scan(&i.ContentID, &i.Decision, &i.ProcessedAt)
	return i, err
}

const createPhoto = `-- name: CreatePhoto :one

INSERT INTO photos (content_id, photo_count, photo_urls, caption_en, caption_ta)
VALUES ($1, $2, $3, $4, $5)
RETURNING content_id, photo_count, photo_urls
`

type CreatePhotoParams struct {
	ContentID  pgtype.UUID
	PhotoCount int32
	PhotoUrls  []string
	CaptionEn  pgtype.Text
	CaptionTa  pgtype.Text
}

type CreatePhotoRow struct {
	ContentID  pgtype.UUID
	PhotoCount int32
	PhotoUrls  []string
}

// --- PHOTOS SPECIFIC ---
func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (CreatePhotoRow, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.ContentID,
		arg.PhotoCount,
		arg.PhotoUrls,
		arg.CaptionEn,
		arg.CaptionTa,
	)
	var i CreatePhotoRow
	err := row.Scan(&i.ContentID, &i.PhotoCount, &i.PhotoUrls)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO user_sessions (user_id, refresh_token, device_info, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token, expires_at, created_at
`

type CreateSessionParams struct {
	UserID       pgtype.UUID
	RefreshToken string
	DeviceInfo   pgtype.Text
	ExpiresAt    pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

// --- USER SESSIONS ---
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshToken,
		arg.DeviceInfo,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStory = `-- name: CreateStory :one

INSERT INTO stories (content_id, headline, body, single_photo_url)
VALUES ($1, $2, $3, $4)
RETURNING content_id, headline, body, single_photo_url
`

type CreateStoryParams struct {
	ContentID      pgtype.UUID
	Headline       string
	Body           string
	SinglePhotoUrl pgtype.Text
}

// --- STORIES SPECIFIC ---
func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRow(ctx, createStory,
		arg.ContentID,
		arg.Headline,
		arg.Body,
		arg.SinglePhotoUrl,
	)
	var i Story
	err := row.Scan(
		&i.ContentID,
		&i.Headline,
		&i.Body,
		&i.SinglePhotoUrl,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, role, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	Role         string
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// --- USERS & AUTH ---
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one

INSERT INTO user_profiles (user_id, full_name, avatar_url, bio)
VALUES ($1, $2, $3, $4)
RETURNING user_id, full_name, avatar_url, bio, created_at, updated_at
`

type CreateUserProfileParams struct {
	UserID    pgtype.UUID
	FullName  string
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
}

// --- USER PROFILES ---
func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.FullName,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVideoLink = `-- name: CreateVideoLink :one

INSERT INTO video_links (content_id, platform, external_video_id, canonical_url, embed_html, thumbnail_url, duration_seconds)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING content_id, platform, external_video_id, canonical_url, embed_html, thumbnail_url, duration_seconds, link_status
`

type CreateVideoLinkParams struct {
	ContentID       pgtype.UUID
	Platform        string
	ExternalVideoID string
	CanonicalUrl    string
	EmbedHtml       pgtype.Text
	ThumbnailUrl    pgtype.Text
	DurationSeconds pgtype.Int4
}

type CreateVideoLinkRow struct {
	ContentID       pgtype.UUID
	Platform        string
	ExternalVideoID string
	CanonicalUrl    string
	EmbedHtml       pgtype.Text
	ThumbnailUrl    pgtype.Text
	DurationSeconds pgtype.Int4
	LinkStatus      string
}

// --- VIDEO LINKS SPECIFIC ---
func (q *Queries) CreateVideoLink(ctx context.Context, arg CreateVideoLinkParams) (CreateVideoLinkRow, error) {
	row := q.db.QueryRow(ctx, createVideoLink,
		arg.ContentID,
		arg.Platform,
		arg.ExternalVideoID,
		arg.CanonicalUrl,
		arg.EmbedHtml,
		arg.ThumbnailUrl,
		arg.DurationSeconds,
	)
	var i CreateVideoLinkRow
	err := row.Scan(
		&i.ContentID,
		&i.Platform,
		&i.ExternalVideoID,
		&i.CanonicalUrl,
		&i.EmbedHtml,
		&i.ThumbnailUrl,
		&i.DurationSeconds,
		&i.LinkStatus,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks
WHERE content_id = $1 AND user_id = $2
`

type DeleteBookmarkParams struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.Exec(ctx, deleteBookmark, arg.ContentID, arg.UserID)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices
WHERE device_token = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, deviceToken pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteDevice, deviceToken)
	return err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows
WHERE follower_user_id = $1 AND followed_user_id = $2
`

type DeleteFollowParams struct {
	FollowerUserID pgtype.UUID
	FollowedUserID pgtype.UUID
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.FollowerUserID, arg.FollowedUserID)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE content_id = $1 AND user_id = $2
`

type DeleteLikeParams struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.ContentID, arg.UserID)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getContentByID = `-- name: GetContentByID :one
SELECT id, title, description, content_type, category_id, district_id, location_id, source_type, source_url, author_user_id, status, moderation_status, verification_status, published_at, created_at, updated_at
FROM content
WHERE id = $1
`

func (q *Queries) GetContentByID(ctx context.Context, id pgtype.UUID) (Content, error) {
	row := q.db.QueryRow(ctx, getContentByID, id)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ContentType,
		&i.CategoryID,
		&i.DistrictID,
		&i.LocationID,
		&i.SourceType,
		&i.SourceUrl,
		&i.AuthorUserID,
		&i.Status,
		&i.ModerationStatus,
		&i.VerificationStatus,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributorProfile = `-- name: GetContributorProfile :one
SELECT user_id, level, points, trust_score, approved_count, rejected_count, report_count, violation_count, featured_count, is_founding_contributor, founding_badge_granted_at, created_at, updated_at
FROM contributor_profiles
WHERE user_id = $1
`

func (q *Queries) GetContributorProfile(ctx context.Context, userID pgtype.UUID) (ContributorProfile, error) {
	row := q.db.QueryRow(ctx, getContributorProfile, userID)
	var i ContributorProfile
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.Points,
		&i.TrustScore,
		&i.ApprovedCount,
		&i.RejectedCount,
		&i.ReportCount,
		&i.ViolationCount,
		&i.FeaturedCount,
		&i.IsFoundingContributor,
		&i.FoundingBadgeGrantedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByContentID = `-- name: GetEventByContentID :one
SELECT content_id, event_name, event_date, start_time, end_time, organizer_name, organizer_contact, interested_count
FROM events
WHERE content_id = $1
`

func (q *Queries) GetEventByContentID(ctx context.Context, contentID pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByContentID, contentID)
	var i Event
	err := row.Scan(
		&i.ContentID,
		&i.EventName,
		&i.EventDate,
		&i.StartTime,
		&i.EndTime,
		&i.OrganizerName,
		&i.OrganizerContact,
		&i.InterestedCount,
	)
	return i, err
}

const getGrievanceByID = `-- name: GetGrievanceByID :one
SELECT id, complainant_user_id, contact_email, category, description, content_id, status, resolution_notes, resolved_at, created_at, updated_at
FROM grievances
WHERE id = $1
`

func (q *Queries) GetGrievanceByID(ctx context.Context, id pgtype.UUID) (Grievance, error) {
	row := q.db.QueryRow(ctx, getGrievanceByID, id)
	var i Grievance
	err := row.Scan(
		&i.ID,
		&i.ComplainantUserID,
		&i.ContactEmail,
		&i.Category,
		&i.Description,
		&i.ContentID,
		&i.Status,
		&i.ResolutionNotes,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestContent = `-- name: GetLatestContent :many

SELECT id, title, description, content_type, category_id, district_id, location_id, source_type, source_url, author_user_id, status, published_at, created_at, updated_at
FROM content
WHERE status = 'PUBLISHED'
ORDER BY published_at DESC, id DESC
LIMIT $1
`

type GetLatestContentRow struct {
	ID           pgtype.UUID
	Title        string
	Description  pgtype.Text
	ContentType  string
	CategoryID   pgtype.UUID
	DistrictID   pgtype.UUID
	LocationID   pgtype.UUID
	SourceType   string
	SourceUrl    pgtype.Text
	AuthorUserID pgtype.UUID
	Status       string
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// --- HOME FEED ---
func (q *Queries) GetLatestContent(ctx context.Context, limit int32) ([]GetLatestContentRow, error) {
	rows, err := q.db.Query(ctx, getLatestContent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestContentRow
	for rows.Next() {
		var i GetLatestContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentType,
			&i.CategoryID,
			&i.DistrictID,
			&i.LocationID,
			&i.SourceType,
			&i.SourceUrl,
			&i.AuthorUserID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikeCount = `-- name: GetLikeCount :one
SELECT COUNT(*) FROM likes WHERE content_id = $1
`

func (q *Queries) GetLikeCount(ctx context.Context, contentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLikeCount, contentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, refresh_token, device_info, is_revoked, expires_at, created_at, updated_at
FROM user_sessions
WHERE refresh_token = $1
`

func (q *Queries) GetSessionByToken(ctx context.Context, refreshToken string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, refreshToken)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.DeviceInfo,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoryByContentID = `-- name: GetStoryByContentID :one
SELECT content_id, headline, body, single_photo_url
FROM stories
WHERE content_id = $1
`

func (q *Queries) GetStoryByContentID(ctx context.Context, contentID pgtype.UUID) (Story, error) {
	row := q.db.QueryRow(ctx, getStoryByContentID, contentID)
	var i Story
	err := row.Scan(
		&i.ContentID,
		&i.Headline,
		&i.Body,
		&i.SinglePhotoUrl,
	)
	return i, err
}

const getUpcomingEvents = `-- name: GetUpcomingEvents :many
SELECT c.id, c.title, c.description, c.category_id, c.district_id, c.author_user_id, c.status, e.event_name, e.event_date, e.start_time, e.end_time, e.organizer_name
FROM content c
JOIN events e ON c.id = e.content_id
WHERE c.status = 'PUBLISHED' AND e.event_date >= $1
ORDER BY e.event_date ASC, c.id DESC
LIMIT $2
`

type GetUpcomingEventsParams struct {
	EventDate pgtype.Timestamptz
	Limit     int32
}

type GetUpcomingEventsRow struct {
	ID            pgtype.UUID
	Title         string
	Description   pgtype.Text
	CategoryID    pgtype.UUID
	DistrictID    pgtype.UUID
	AuthorUserID  pgtype.UUID
	Status        string
	EventName     string
	EventDate     pgtype.Timestamptz
	StartTime     pgtype.Text
	EndTime       pgtype.Text
	OrganizerName string
}

func (q *Queries) GetUpcomingEvents(ctx context.Context, arg GetUpcomingEventsParams) ([]GetUpcomingEventsRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingEvents, arg.EventDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingEventsRow
	for rows.Next() {
		var i GetUpcomingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.DistrictID,
			&i.AuthorUserID,
			&i.Status,
			&i.EventName,
			&i.EventDate,
			&i.StartTime,
			&i.EndTime,
			&i.OrganizerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, full_name, avatar_url, bio, created_at, updated_at
FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoLinkByContentID = `-- name: GetVideoLinkByContentID :one
SELECT content_id, platform, external_video_id, canonical_url, embed_html, thumbnail_url, duration_seconds, link_status, last_checked_at, created_at
FROM video_links
WHERE content_id = $1
`

func (q *Queries) GetVideoLinkByContentID(ctx context.Context, contentID pgtype.UUID) (VideoLink, error) {
	row := q.db.QueryRow(ctx, getVideoLinkByContentID, contentID)
	var i VideoLink
	err := row.Scan(
		&i.ContentID,
		&i.Platform,
		&i.ExternalVideoID,
		&i.CanonicalUrl,
		&i.EmbedHtml,
		&i.ThumbnailUrl,
		&i.DurationSeconds,
		&i.LinkStatus,
		&i.LastCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, created_at
FROM categories
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByContentID = `-- name: ListCommentsByContentID :many
SELECT id, content_id, user_id, body, created_at, updated_at
FROM comments
WHERE content_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByContentID(ctx context.Context, contentID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByContentID, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentByCategoryPaginated = `-- name: ListContentByCategoryPaginated :many

SELECT id, title, description, content_type, category_id, district_id, location_id, source_type, source_url, author_user_id, status, published_at, created_at, updated_at
FROM content
WHERE status = 'PUBLISHED'
  AND category_id = $1
  AND (published_at < $2 OR (published_at = $2 AND id < $3))
ORDER BY published_at DESC, id DESC
LIMIT $4
`

type ListContentByCategoryPaginatedParams struct {
	CategoryID  pgtype.UUID
	PublishedAt pgtype.Timestamptz
	ID          pgtype.UUID
	Limit       int32
}

type ListContentByCategoryPaginatedRow struct {
	ID           pgtype.UUID
	Title        string
	Description  pgtype.Text
	ContentType  string
	CategoryID   pgtype.UUID
	DistrictID   pgtype.UUID
	LocationID   pgtype.UUID
	SourceType   string
	SourceUrl    pgtype.Text
	AuthorUserID pgtype.UUID
	Status       string
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// --- CATEGORY FEED ---
func (q *Queries) ListContentByCategoryPaginated(ctx context.Context, arg ListContentByCategoryPaginatedParams) ([]ListContentByCategoryPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listContentByCategoryPaginated,
		arg.CategoryID,
		arg.PublishedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentByCategoryPaginatedRow
	for rows.Next() {
		var i ListContentByCategoryPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentType,
			&i.CategoryID,
			&i.DistrictID,
			&i.LocationID,
			&i.SourceType,
			&i.SourceUrl,
			&i.AuthorUserID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentPaginated = `-- name: ListContentPaginated :many
SELECT id, title, description, content_type, category_id, district_id, location_id, source_type, source_url, author_user_id, status, published_at, created_at
FROM content
WHERE status = 'PUBLISHED'
  AND (published_at < $1 OR (published_at = $1 AND id < $2))
ORDER BY published_at DESC, id DESC
LIMIT $3
`

type ListContentPaginatedParams struct {
	PublishedAt pgtype.Timestamptz
	ID          pgtype.UUID
	Limit       int32
}

type ListContentPaginatedRow struct {
	ID           pgtype.UUID
	Title        string
	Description  pgtype.Text
	ContentType  string
	CategoryID   pgtype.UUID
	DistrictID   pgtype.UUID
	LocationID   pgtype.UUID
	SourceType   string
	SourceUrl    pgtype.Text
	AuthorUserID pgtype.UUID
	Status       string
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListContentPaginated(ctx context.Context, arg ListContentPaginatedParams) ([]ListContentPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listContentPaginated, arg.PublishedAt, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentPaginatedRow
	for rows.Next() {
		var i ListContentPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentType,
			&i.CategoryID,
			&i.DistrictID,
			&i.LocationID,
			&i.SourceType,
			&i.SourceUrl,
			&i.AuthorUserID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistricts = `-- name: ListDistricts :many

SELECT id, name, created_at
FROM districts
ORDER BY name ASC
`

// --- GEOGRAPHIC & TAXONOMY ---
func (q *Queries) ListDistricts(ctx context.Context) ([]District, error) {
	rows, err := q.db.Query(ctx, listDistricts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []District
	for rows.Next() {
		var i District
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingModerationQueue = `-- name: ListPendingModerationQueue :many

SELECT id, title, description, content_type, category_id, district_id, location_id, source_type, source_url, author_user_id, status, moderation_status, verification_status, published_at, created_at, updated_at
FROM content
WHERE status = 'PENDING' OR moderation_status = 'QUARANTINE'
ORDER BY created_at ASC
LIMIT $1
`

// --- MODERATION & AUDIT ---
func (q *Queries) ListPendingModerationQueue(ctx context.Context, limit int32) ([]Content, error) {
	rows, err := q.db.Query(ctx, listPendingModerationQueue, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentType,
			&i.CategoryID,
			&i.DistrictID,
			&i.LocationID,
			&i.SourceType,
			&i.SourceUrl,
			&i.AuthorUserID,
			&i.Status,
			&i.ModerationStatus,
			&i.VerificationStatus,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE user_sessions
SET is_revoked = TRUE, updated_at = NOW()
WHERE refresh_token = $1
RETURNING id, is_revoked, updated_at
`

type RevokeSessionRow struct {
	ID        pgtype.UUID
	IsRevoked bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSession(ctx context.Context, refreshToken string) (RevokeSessionRow, error) {
	row := q.db.QueryRow(ctx, revokeSession, refreshToken)
	var i RevokeSessionRow
	err := row.Scan(&i.ID, &i.IsRevoked, &i.UpdatedAt)
	return i, err
}

const searchContent = `-- name: SearchContent :many

SELECT id, title, description, content_type, category_id, district_id, location_id, source_type, source_url, author_user_id, status, published_at, created_at, updated_at
FROM content
WHERE status = 'PUBLISHED'
  AND (
    title ILIKE '%' || $1 || '%' OR COALESCE(description, '') ILIKE '%' || $1 || '%'
  )
ORDER BY published_at DESC, id DESC
LIMIT $2
`

type SearchContentParams struct {
	Column1 pgtype.Text
	Limit   int32
}

type SearchContentRow struct {
	ID           pgtype.UUID
	Title        string
	Description  pgtype.Text
	ContentType  string
	CategoryID   pgtype.UUID
	DistrictID   pgtype.UUID
	LocationID   pgtype.UUID
	SourceType   string
	SourceUrl    pgtype.Text
	AuthorUserID pgtype.UUID
	Status       string
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// --- SEARCH & DISCOVERY ---
func (q *Queries) SearchContent(ctx context.Context, arg SearchContentParams) ([]SearchContentRow, error) {
	rows, err := q.db.Query(ctx, searchContent, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchContentRow
	for rows.Next() {
		var i SearchContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ContentType,
			&i.CategoryID,
			&i.DistrictID,
			&i.LocationID,
			&i.SourceType,
			&i.SourceUrl,
			&i.AuthorUserID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentStatus = `-- name: UpdateContentStatus :one
UPDATE content
SET status = $2, moderation_status = $3, published_at = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, status, moderation_status, published_at
`

type UpdateContentStatusParams struct {
	ID               pgtype.UUID
	Status           string
	ModerationStatus string
	PublishedAt      pgtype.Timestamptz
}

type UpdateContentStatusRow struct {
	ID               pgtype.UUID
	Status           string
	ModerationStatus string
	PublishedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateContentStatus(ctx context.Context, arg UpdateContentStatusParams) (UpdateContentStatusRow, error) {
	row := q.db.QueryRow(ctx, updateContentStatus,
		arg.ID,
		arg.Status,
		arg.ModerationStatus,
		arg.PublishedAt,
	)
	var i UpdateContentStatusRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ModerationStatus,
		&i.PublishedAt,
	)
	return i, err
}

const updateContributorReputation = `-- name: UpdateContributorReputation :one
UPDATE contributor_profiles
SET points = $2, trust_score = $3, level = $4, updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, level, points, trust_score
`

type UpdateContributorReputationParams struct {
	UserID     pgtype.UUID
	Points     int32
	TrustScore int32
	Level      string
}

type UpdateContributorReputationRow struct {
	UserID     pgtype.UUID
	Level      string
	Points     int32
	TrustScore int32
}

func (q *Queries) UpdateContributorReputation(ctx context.Context, arg UpdateContributorReputationParams) (UpdateContributorReputationRow, error) {
	row := q.db.QueryRow(ctx, updateContributorReputation,
		arg.UserID,
		arg.Points,
		arg.TrustScore,
		arg.Level,
	)
	var i UpdateContributorReputationRow
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.Points,
		&i.TrustScore,
	)
	return i, err
}

const updateFoundingStatus = `-- name: UpdateFoundingStatus :one
UPDATE contributor_profiles
SET is_founding_contributor = $2, founding_badge_granted_at = $3, updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, is_founding_contributor, founding_badge_granted_at
`

type UpdateFoundingStatusParams struct {
	UserID                 pgtype.UUID
	IsFoundingContributor  bool
	FoundingBadgeGrantedAt pgtype.Timestamptz
}

type UpdateFoundingStatusRow struct {
	UserID                 pgtype.UUID
	IsFoundingContributor  bool
	FoundingBadgeGrantedAt pgtype.Timestamptz
}

func (q *Queries) UpdateFoundingStatus(ctx context.Context, arg UpdateFoundingStatusParams) (UpdateFoundingStatusRow, error) {
	row := q.db.QueryRow(ctx, updateFoundingStatus, arg.UserID, arg.IsFoundingContributor, arg.FoundingBadgeGrantedAt)
	var i UpdateFoundingStatusRow
	err := row.Scan(&i.UserID, &i.IsFoundingContributor, &i.FoundingBadgeGrantedAt)
	return i, err
}

const updateGrievanceStatus = `-- name: UpdateGrievanceStatus :one
UPDATE grievances
SET status = $2, resolution_notes = $3, resolved_at = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, status, resolution_notes, resolved_at
`

type UpdateGrievanceStatusParams struct {
	ID              pgtype.UUID
	Status          string
	ResolutionNotes pgtype.Text
	ResolvedAt      pgtype.Timestamptz
}

type UpdateGrievanceStatusRow struct {
	ID              pgtype.UUID
	Status          string
	ResolutionNotes pgtype.Text
	ResolvedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateGrievanceStatus(ctx context.Context, arg UpdateGrievanceStatusParams) (UpdateGrievanceStatusRow, error) {
	row := q.db.QueryRow(ctx, updateGrievanceStatus,
		arg.ID,
		arg.Status,
		arg.ResolutionNotes,
		arg.ResolvedAt,
	)
	var i UpdateGrievanceStatusRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ResolutionNotes,
		&i.ResolvedAt,
	)
	return i, err
}
